source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


abstract_target 'Pod' do
    pod 'CDBKit', :path => '../'
    
    target 'CDBKit_Example' do
        platform :ios, '8.0'
        target 'CDBKit_Tests' do
            inherit! :search_paths
        end
    end
    
    target 'CDBKit_Mac_Example' do
        platform :osx, '10.8'
    end
end
